const all_settings = {
  system: {
    "braille_type": {
      id: "braille_type",
      name: "Type de braille",
      type: "menu",
      values: ["dot-8", "grade1", "grade2"],
      default: "dot-8",
    },
    "auto_sync_date": {
      id: "auto_sync_date",
      name: "Synchronisation automatique de la date",
      type: "checkbox",
      default: false,
    },
    "spaces_in_label": {
      id: "space_in_label",
      name: "Espace dans les éléments",
      type: "checkbox",
      default: false,
    },
    "shortcuts_visible": {
      id: "shortcuts_visible",
      name: "Raccourcis clavier visibles",
      type: "checkbox",
      default: false,
    },
    "app_explorer": {
      id: "app_explorer",
      name: "Explorateur",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "main_apps_menu",
    },
    "app_settings": {
      id: "app_settings",
      name: "Préférences",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "main_apps_menu",
    },
    "app_agenda": {
      id: "app_agenda",
      name: "Agenda",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_radio": {
      id: "app_radio",
      name: "Radio",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_mp3": {
      id: "app_mp3",
      name: "MP3",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_timer": {
      id: "app_timer",
      name: "Chronomètre",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_translator": {
      id: "app_translator",
      name: "Traducteur",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_wikipedia": {
      id: "app_wikipedia",
      name: "Wikipedia",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_write_word": {
      id: "app_write_word",
      name: "Écrire un mot",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_operation": {
      id: "app_operation",
      name: "Opération",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_mines": {
      id: "app_mines",
      name: "Démineur",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "app_mastermind": {
      id: "app_mastermind",
      name: "Mastermind",
      type: "menu",
      values: ["invisible", "main_apps_menu", "more_apps_menu"],
      default: "invisible",
    },
    "developer": {
      id: "developer",
      name: "Développeur",
      type: "checkbox",
      default: false,
    },
  },
  explorer: {
    "empty_bluetooth_shutdown": {
      id: "empty_bluetooth_shutdown",
      name: "Vider le dossier bluetooth à l'extinction",
      type: "checkbox",
      default: false,
    },
    "empty_trash_shutdown": {
      id: "empty_trash_shutdown",
      name: "Vider la corbeille à l'extinction",
      type: "checkbox",
      default: false,
    },
    "number_recent_files": {
      id: "number_recent_files",
      name: "Nombre de fichiers récents",
      type: "number",
      min: 1,
      max: 30,
      default: 10,
    },
  },
  editor: {
    "braille_type": {
      id: "braille_type",
      name: "Type de braille",
      type: "menu",
      values: ["dot-8", "grade1", "grade2"],
      default: "dot-8",
    },
    "line_length": {
      id: "line_length",
      name: "Longueur de ligne",
      type: "number",
      min: 1,
      max: 160,
      default: 80,
    },
    "dot78_visible": {
      id: "dot78_visible",
      name: "Points 7 et 8 visibles",
      type: "checkbox",
      default: true,
    },
    "cursor_visible": {
      id: "cursor_visible",
      name: "Curseur visible",
      type: "checkbox",
      default: true,
    },
    "forward_display_mode": {
      id: "forward_display_mode",
      name: "Avance de l'afficheur braille",
      type: "menu",
      values: ["normal", "significative"],
    },
    "autoscroll": {
      id: "autoscroll",
      name: "Défilement automatique",
      type: "number",
      min: 2,
      max: 120,
      default: 5,
    },
  },
  math: {
    "angle": {
      id: "angle",
      name: "Unité d'angle",
      type: "menu",
      values: ["degree", "radian"],
      default: "radian",
    },
    "fraction": {
      id: "fraction",
      name: "Fraction",
      type: "checkbox",
      default: true,
    },
    "precision": {
      id: "precision",
      name: "Précision",
      type: "number",
      min: 0,
      max: 8,
      default: 2,
    },
    "format": {
      id: "format",
      name: "Format",
      type: "menu",
      values: ["scientific", "normal"],
      default: "scientific",
    },
  },
  "music_xml": {
    "edit_mode": {
      id: "edit_mode",
      name: "Mode d'édition",
      type: "menu",
      values: ["expert", "read", "edit", "listen"],
      default: "read",
    },
    "braille_type": {
      id: "braille_type",
      name: "Type de braille",
      type: "menu",
      values: ["dot-8", "grade1"],
      default: "dot-8",
    },
    "notes_dots": {
      id: "notes_dots",
      name: "Points des notes",
      type: "menu",
      values: ["8_dots", "6_dots", "6_dots_with_group"],
      default: "6_dots_with_group",
    },
    "ascending_chords": {
      id: "ascending_chords",
      name: "Intervals ascendants",
      type: "checkbox",
      default: true,
    },
    "fingering": {
      id: "fingering",
      name: "Doigté",
      type: "checkbox",
      default: true,
    },
    "clef": {
      id: "clef",
      name: "Clé",
      type: "checkbox",
      default: true,
    },
    "parts": {
      id: "parts",
      name: "Parties",
      type: "menu",
      values: ["name", "abbreviation"],
      default: "name",
    },
    "measure_b123": {
      id: "measure_b123",
      name: "Mesure avec les points 123",
      type: "checkbox",
      default: false,
    },
    "measure_number": {
      id: "measure_number",
      name: "Numéro de mesure",
      type: "checkbox",
      default: false,
    },
    "measure_every": {
      id: "measure_every",
      name: "Numéro de mesure tous les",
      type: "number",
      min: 1,
      max: 100,
      default: 1,
    },
    "view": {
      id: "view",
      name: "Vue",
      type: "menu",
      values: ["by_section", "by_part"],
      default: "by_section",
    },
    "section": {
      id: "section",
      name: "Section",
      type: "menu",
      values: ["total_part", "system", "number"],
      default: "total_part",
    },
    "measures_per_section": {
      id: "measures_per_section",
      name: "Mesures par section",
      type: "number",
      min: 1,
      max: 100,
      default: 8,
    },
    "words": {
      id: "words",
      name: "Mots",
      type: "checkbox",
      default: true,
    },
    "credit_words": {
      id: "credit_words",
      name: "Crédits",
      type: "checkbox",
      default: true,
    },
    "lyrics": {
      id: "lyrics",
      name: "Paroles",
      type: "menu",
      values: ["no", "after_each_note", "before_each_section", "after_each_section"],
      default: "no",
    },
  },
  "music_bxml": {
    "edit_mode": {
      id: "edit_mode",
      name: "Mode d'édition",
      type: "menu",
      values: ["expert", "read", "edit", "listen"],
      default: "read",
    },
    "braille_type": {
      id: "braille_type",
      name: "Type de braille",
      type: "menu",
      values: ["dot-8", "grade1"],
      default: "dot-8",
    },
    "notes_dots": {
      id: "notes_dots",
      name: "Points des notes",
      type: "menu",
      values: ["8_dots", "6_dots", "6_dots_with_group"],
      default: "6_dots_with_group",
    },
    "ascending_chords": {
      id: "ascending_chords",
      name: "Intervals ascendants",
      type: "checkbox",
      default: true,
    },
    "fingering": {
      id: "fingering",
      name: "Doigté",
      type: "checkbox",
      default: true,
    },
    "clef": {
      id: "clef",
      name: "Clé",
      type: "checkbox",
      default: true,
    },
    "parts": {
      id: "parts",
      name: "Parties",
      type: "menu",
      values: ["name", "abbreviation"],
      default: "name",
    },
    "measure_b123": {
      id: "measure_b123",
      name: "Mesure avec les points 123",
      type: "checkbox",
      default: false,
    },
    "measure_number": {
      id: "measure_number",
      name: "Numéro de mesure",
      type: "checkbox",
      default: false,
    },
    "measure_every": {
      id: "measure_every",
      name: "Numéro de mesure tous les",
      type: "number",
      min: 1,
      max: 100,
      default: 1,
    },
    "view": {
      id: "view",
      name: "Vue",
      type: "menu",
      values: ["by_section", "by_part"],
      default: "by_section",
    },
    "section": {
      id: "section",
      name: "Section",
      type: "menu",
      values: ["total_part", "system", "number"],
      default: "total_part",
    },
    "measures_per_section": {
      id: "measures_per_section",
      name: "Mesures par section",
      type: "number",
      min: 1,
      max: 100,
      default: 8,
    },
    "words": {
      id: "words",
      name: "Mots",
      type: "checkbox",
      default: true,
    },
    "credit_words": {
      id: "credit_words",
      name: "Crédits",
      type: "checkbox",
      default: true,
    },
    "lyrics": {
      id: "lyrics",
      name: "Paroles",
      type: "menu",
      values: ["no", "after_each_note", "before_each_section", "after_each_section"],
      default: "no",
    },
    "karaoke": {
      id: "karaoke",
      name: "Karaoké",
      type: "checkbox",
      default: true,
    },
  },
};

const settings_value = {
  "dot-8": "Braille informatique (8 points)",
  "grade1": "Braille intégral (6 points",
  "grade2": "Braille abrégé (6 points)",
  "main_apps_menu": "Menu principal",
  "more_apps_menu": "Sous menu plus d'apps",
  "invisible": "Invisible",
  "normal": "Normal",
  "significative": "Significative",
  "degree": "Degré",
  "radian": "Radian",
  "scientific": "Scientifique",
  "expert": "Expert",
  "read": "Lecture",
  "edit": "Édition",
  "listen": "Écoute",
  "8_dots": "8 points",
  "6_dots": "6 points",
  "6_dots_with_group": "6 points avec groupes",
  "name": "Nom",
  "abbreviation": "Abréviation",
  "by_section": "Par section",
  "by_part": "Par partie",
  "total_part": "Partie complète",
  "system": "Système",
  "number": "Numéro",
  "no": "Non",
  "after_each_note": "Après chaque note",
  "before_each_section": "Avant chaque section",
  "after_each_section": "Après chaque section",
};

const settings = { all_settings: all_settings, settings_value: settings_value };
export default settings;
