name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Get project version
        id: get_version
        run: echo "version=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV

      - name: Build project
        run: |
          npm run build
          npm run build:all

      # Remplace la création de release par la version obtenue
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          draft: false
          prerelease: false

      # Upload assets
      - name: Upload Mac x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/build/bnote-settings-mac-x64.dmg
          asset_name: bnote-settings-mac-x64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Mac arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/build/bnote-settings-mac-arm64.dmg
          asset_name: bnote-settings-mac-arm64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/build/bnote-settings-win-x64.exe
          asset_name: bnote-settings-win-x64.exe
          asset_content_type: application/octet-stream
