name: Build Electron Apps

on:
  push:
    branches:
      - copilot/fix-367
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-electron:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests and lint
        run: |
          npm run test
          npm run lint

      - name: Build web application
        run: npm run build

      - name: Build Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run electron:build:mac
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Build Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run electron:build:win

      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            dist_electron/*.dmg
            dist_electron/*.zip

      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist_electron/*.exe

#      - name: Release macOS
#        if: matrix.os == 'macos-latest' && github.event_name == 'release'
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            dist_electron/*.dmg
#            dist_electron/*.zip
#          tag_name: ${{ github.event.release.tag_name }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Release Windows
#        if: matrix.os == 'windows-latest' && github.event_name == 'release'
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            dist_electron/*.exe
#          tag_name: ${{ github.event.release.tag_name }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
