name: Build and Release

on:
  push:
    tags:
      - '*'

permissions: write-all

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build project and determine if prerelease
        id: prerelease
        run: |
          npm run build
          npm run build:mac
          if [[ "${{ github.ref_name }}" == *"beta"* || "${{ github.ref_name }}" == *"alpha"* ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ env.prerelease }}
          files:
            'dist/build/bnote-settings.dmg'
