# This workflow comments on a pull request when it’s merged
on:
  pull_request:
    types:
      - closed

jobs:
  comment-close-pull-request:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.actor != 'dependabot[bot]' && github.actor != 'theotime2005'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Comment pull request
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -b "This pull request has been merged and closed. Thank you for your contribution! 🎉
            Your work will be published in the feature deployment."
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
