name: Update packages

on:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout to the main branch
        run: git checkout main

      - name: Setup node js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 'latest'

      - name: Install packages
        run: npm install

      - name: Update packages
        run: npm update

      - name: Check if tests pass
        run: npx vitest run

      - name: Commit and push changes
        run: |
          git config --global user.name "bnote-settings-packages-updater"
          git config --global user.email "bnote-settings-packages-updater@users.noreply.github.com"
          commit_date=$(date)
          git add .
          git commit -m "Update package on $commit_date"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
