name: Update .nvmrc to latest Node.js

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 1'

jobs:
  update-nvmrc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: node

      - name: Check if node version is up to date
        id: check_version
        run: |
          current_version=$(cat .nvmrc)
          latest_version=$(node -v | sed 's/^v//')
          echo "latest_node_version=$latest_version" >> $GITHUB_ENV
          if [ "$current_version" = "$latest_version" ]; then
            echo "up_to_date=true" >> $GITHUB_ENV
          else
            echo "up_to_date=false" >> $GITHUB_ENV
          fi

      - name: Create or Update branch and PR
        if: env.up_to_date == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions-updater"
          git config --local user.email "github-actions-updater@github.com"

          BRANCH_NAME="update-nvmrc-${{ env.latest_node_version }}"


          if git ls-remote --heads origin $BRANCH_NAME | grep -q $BRANCH_NAME; then
            echo "Branch $BRANCH_NAME already exists"
            git fetch origin $BRANCH_NAME
            git checkout $BRANCH_NAME
          else
            echo "Création of $BRANCH_NAME branch."
            git checkout -b $BRANCH_NAME
          fi

          echo "${{ env.latest_node_version }}" > .nvmrc

          if [[ -n $(git status --porcelain) ]]; then
            git add .nvmrc
            git commit -m "Update .nvmrc to Node.js ${{ env.latest_node_version }}"
            git push --set-upstream origin $BRANCH_NAME
          fi

          EXISTING_PR=$(gh pr list --head $BRANCH_NAME --status open --json number -q '.[0].number')

          if [ -z "$EXISTING_PR" ]; then
            echo "Pull request creation."
            PR_URL=$(gh pr create --title "bump: Update .nvmrc to Node.js ${{ env.latest_node_version }}" --body "This PR updates the .nvmrc file to the latest Node.js version ${{ env.latest_node_version }}." --base main --head $BRANCH_NAME)
            echo "PR_URL=$PR_URL" >> "$GITHUB_ENV"

            gh pr merge "$PR_URL" --auto -s -d
          else
            echo "Pull request already exists for this branch (#$EXISTING_PR). No actions required."
          fi
